### ISSUE TITLE
请求收入到OpenWHU项目

### ISSUE THREAD

**Issue by Crescentm** [Miles629/DouTu#27]
想把学长您的实验资料收集进OpenWHU项目，望批准❤
[项目地址](https://github.com/openwhu/OpenWHU)

**Comment by Miles629** [comment]
ok。请随意使用。收录到哪个页面可以返我一个链接吗？

**Comment by Crescentm** [comment]
能问一下学长是什么院系的吗😆

**Comment by Miles629** [comment]
> 能问一下学长是什么院系的吗😆

计算机学院。软件工程。

**Comment by Crescentm** [comment]
https://github.com/openwhu/OpenWHU/tree/master/%E4%B8%93%E4%B8%9A%E8%AF%BE/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%AD%A6%E9%99%A2/%E8%BD%AF%E4%BB%B6%E6%9E%84%E9%80%A0%E5%9F%BA%E7%A1%80/2018%E7%BA%A7%E5%A4%A7%E4%BD%9C%E4%B8%9A(C%23C%23)
再次感谢学长，真的谢谢你。
