### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by StLeoX** [Miles629/DouTu#28]
can you give more details?

**Comment by Miles629** [comment]
I'm glad you're interested in my project. I need to tell you that this project is a big assignment of my C # course. So if you want to run it, please make sure that C # freework is configured in your system. I recommend that you download the whole project source file and open the whole project file through vs.
It is worth mentioning that the database configuration should be modified to your own database information.
We have integrated OCR API in the project. This API is provided by Baidu. At first, it does not support our framework, but we modify it to make it usable. The specific use of OCR API can be retrieved in Baidu API.
 Ask me if you have any other questions.
